name: Re-push Repository Every 24 Hours

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the job every day at midnight (UTC)

jobs:
  repush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Force push to trigger CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git commit --allow-empty -m "Trigger CI via GitHub Actions"
          git push origin main
